// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: url_ticker.proto

package sample.grpc;

public interface LinkTitlesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LinkTitlesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string topic = 2;</code>
   */
  java.lang.String getTopic();
  /**
   * <code>string topic = 2;</code>
   */
  com.google.protobuf.ByteString
      getTopicBytes();
}
