// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: url_ticker.proto

package sample.grpc;

public interface UrlRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UrlRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
